/**
 * Seed data for demo workers
 */

const CITY_COORDS = {
  'Delhi': { lat: 28.6139, lng: 77.2090 },
  'Mumbai': { lat: 19.0760, lng: 72.8777 },
  'Bengaluru': { lat: 12.9716, lng: 77.5946 },
  'Chennai': { lat: 13.0827, lng: 80.2707 },
};

export const SEED_WORKERS = [
  {
    workerId: 'W001',
    name: 'Ravi Sharma',
    homeCity: 'Delhi',
    shiftActive: false,
    lastGPS_lat: 28.6139,
    lastGPS_lng: 77.2090,
    lastGPS_city: 'Delhi',
    lastIP: '103.21.58.192',
    isMockLocation: false,
    payoutStatus: 'NONE',
    payoutAmount: 0,
    avatar: 'blue',
  },
  {
    workerId: 'W002',
    name: 'Priya Nair',
    homeCity: 'Mumbai',
    shiftActive: false,
    lastGPS_lat: 19.0760,
    lastGPS_lng: 72.8777,
    lastGPS_city: 'Mumbai',
    lastIP: '49.36.128.45',
    isMockLocation: false,
    payoutStatus: 'NONE',
    payoutAmount: 0,
    avatar: 'purple',
  },
  {
    workerId: 'W003',
    name: 'Arjun Singh',
    homeCity: 'Bengaluru',
    shiftActive: false,
    lastGPS_lat: 12.9716,
    lastGPS_lng: 77.5946,
    lastGPS_city: 'Bengaluru',
    lastIP: '106.51.72.133',
    isMockLocation: false,
    payoutStatus: 'NONE',
    payoutAmount: 0,
    avatar: 'green',
  },
  {
    workerId: 'W004',
    name: 'Fake User 1',
    homeCity: 'Delhi',
    shiftActive: false,
    lastGPS_lat: 19.0823,
    lastGPS_lng: 72.8812,
    lastGPS_city: 'Mumbai',
    lastIP: '182.73.111.222',
    isMockLocation: true,
    payoutStatus: 'NONE',
    payoutAmount: 0,
    avatar: 'red',
  },
  {
    workerId: 'W005',
    name: 'Fake User 2',
    homeCity: 'Chennai',
    shiftActive: false,
    lastGPS_lat: 19.0544,
    lastGPS_lng: 72.8406,
    lastGPS_city: 'Mumbai',
    lastIP: '223.178.44.88',
    isMockLocation: false,
    payoutStatus: 'NONE',
    payoutAmount: 0,
    avatar: 'indigo',
  },
  {
  workerId: 'W006',
  name: 'Ananya Gupta',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.7041,
  lastGPS_lng: 77.1025,
  lastGPS_city: 'Delhi',
  lastIP: '122.162.45.201',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'teal',
},
{
  workerId: 'W007',
  name: 'Karan Mehta',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.2183,
  lastGPS_lng: 72.9781,
  lastGPS_city: 'Mumbai',
  lastIP: '49.37.210.14',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'cyan',
},
{
  workerId: 'W008',
  name: 'Sneha Reddy',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9352,
  lastGPS_lng: 77.6245,
  lastGPS_city: 'Bengaluru',
  lastIP: '106.51.88.219',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'pink',
},
{
  workerId: 'W009',
  name: 'Vikram Joshi',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 13.0674,
  lastGPS_lng: 80.2376,
  lastGPS_city: 'Chennai',
  lastIP: '157.49.112.63',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'amber',
},
{
  workerId: 'W010',
  name: 'Meera Iyer',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.0330,
  lastGPS_lng: 72.8597,
  lastGPS_city: 'Mumbai',
  lastIP: '59.183.92.144',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'indigo',
},

{
  workerId: 'W011',
  name: 'Rahul Verma',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.5355,
  lastGPS_lng: 77.3910,
  lastGPS_city: 'Delhi',
  lastIP: '103.86.18.77',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'lime',
},
{
  workerId: 'W012',
  name: 'Pooja Kulkarni',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 13.0067,
  lastGPS_lng: 77.5649,
  lastGPS_city: 'Bengaluru',
  lastIP: '117.239.33.201',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'violet',
},
{
  workerId: 'W013',
  name: 'Aditya Rao',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 13.1067,
  lastGPS_lng: 80.2206,
  lastGPS_city: 'Chennai',
  lastIP: '49.205.67.92',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'emerald',
},
{
  workerId: 'W014',
  name: 'Neha Kapoor',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.4595,
  lastGPS_lng: 77.0266,
  lastGPS_city: 'Delhi',
  lastIP: '14.194.55.130',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'rose',
},
{
  workerId: 'W015',
  name: 'Siddharth Jain',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.1136,
  lastGPS_lng: 72.8697,
  lastGPS_city: 'Mumbai',
  lastIP: '98.176.44.210',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'sky',
},

{
  workerId: 'W016',
  name: 'Ishita Banerjee',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9279,
  lastGPS_lng: 77.6271,
  lastGPS_city: 'Bengaluru',
  lastIP: '115.97.201.88',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'mint',
},
{
  workerId: 'W017',
  name: 'Rohit Malhotra',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.4089,
  lastGPS_lng: 77.3178,
  lastGPS_city: 'Delhi',
  lastIP: '223.190.12.45',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'navy',
},
{
  workerId: 'W018',
  name: 'Kavya Nambiar',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 12.9815,
  lastGPS_lng: 80.2180,
  lastGPS_city: 'Chennai',
  lastIP: '61.2.144.199',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'peach',
},
{
  workerId: 'W019',
  name: 'Manish Tiwari',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.0176,
  lastGPS_lng: 72.8562,
  lastGPS_city: 'Mumbai',
  lastIP: '27.60.88.31',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'slate',
},
{
  workerId: 'W020',
  name: 'Divya Pillai',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9141,
  lastGPS_lng: 77.6100,
  lastGPS_city: 'Bengaluru',
  lastIP: '49.204.201.155',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'coral',
},

{
  workerId: 'W021',
  name: 'Amit Choudhary',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.6692,
  lastGPS_lng: 77.4538,
  lastGPS_city: 'Delhi',
  lastIP: '103.48.201.92',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'gold',
},
{
  workerId: 'W022',
  name: 'Farah Khan',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.0769,
  lastGPS_lng: 72.8770,
  lastGPS_city: 'Mumbai',
  lastIP: '182.64.233.18',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'magenta',
},
{
  workerId: 'W023',
  name: 'Nikhil Deshpande',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 13.0358,
  lastGPS_lng: 77.5970,
  lastGPS_city: 'Bengaluru',
  lastIP: '106.203.77.61',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'steel',
},
{
  workerId: 'W024',
  name: 'Lakshmi Narayan',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 13.0475,
  lastGPS_lng: 80.2110,
  lastGPS_city: 'Chennai',
  lastIP: '157.51.90.204',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'bronze',
},
{
  workerId: 'W025',
  name: 'Harsh Vardhan',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.6328,
  lastGPS_lng: 77.2197,
  lastGPS_city: 'Delhi',
  lastIP: '59.97.188.140',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'olive',
},

{
  workerId: 'W026',
  name: 'Tanya Arora',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.0896,
  lastGPS_lng: 72.8656,
  lastGPS_city: 'Mumbai',
  lastIP: '27.57.210.99',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'plum',
},
{
  workerId: 'W027',
  name: 'Gautam Shetty',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9762,
  lastGPS_lng: 77.6033,
  lastGPS_city: 'Bengaluru',
  lastIP: '106.208.145.73',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'aqua',
},
{
  workerId: 'W028',
  name: 'Shruti Menon',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 13.0604,
  lastGPS_lng: 80.2496,
  lastGPS_city: 'Chennai',
  lastIP: '49.37.166.201',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'crimson',
},
{
  workerId: 'W029',
  name: 'Yash Patel',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.1963,
  lastGPS_lng: 72.8220,
  lastGPS_city: 'Mumbai',
  lastIP: '122.170.55.63',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'charcoal',
},
{
  workerId: 'W030',
  name: 'Komal Bansal',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.7041,
  lastGPS_lng: 77.1025,
  lastGPS_city: 'Delhi',
  lastIP: '150.129.88.201',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'lavender',
},

{
  workerId: 'W031',
  name: 'Abhishek Roy',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9718,
  lastGPS_lng: 77.6412,
  lastGPS_city: 'Bengaluru',
  lastIP: '117.198.201.44',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'sand',
},
{
  workerId: 'W032',
  name: 'Nandini Rao',
  homeCity: 'Chennai',
  shiftActive: false,
  lastGPS_lat: 13.0825,
  lastGPS_lng: 80.2750,
  lastGPS_city: 'Chennai',
  lastIP: '61.12.77.155',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'ruby',
},
{
  workerId: 'W033',
  name: 'Varun Khanna',
  homeCity: 'Delhi',
  shiftActive: false,
  lastGPS_lat: 28.6135,
  lastGPS_lng: 77.2370,
  lastGPS_city: 'Delhi',
  lastIP: '103.25.201.77',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'sapphire',
},
{
  workerId: 'W034',
  name: 'Ritika Sen',
  homeCity: 'Mumbai',
  shiftActive: false,
  lastGPS_lat: 19.0822,
  lastGPS_lng: 72.8417,
  lastGPS_city: 'Mumbai',
  lastIP: '182.75.199.32',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'ivory',
},
{
  workerId: 'W035',
  name: 'Deepak Yadav',
  homeCity: 'Bengaluru',
  shiftActive: false,
  lastGPS_lat: 12.9698,
  lastGPS_lng: 77.7500,
  lastGPS_city: 'Bengaluru',
  lastIP: '106.221.54.188',
  isMockLocation: false,
  payoutStatus: 'NONE',
  payoutAmount: 0,
  avatar: 'copper',
},
];

export function getCityCoords(city) {
  return CITY_COORDS[city] || { lat: 20.5937, lng: 78.9629 };
}
